-- Find the total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM
	customers
GROUP BY
	country
ORDER BY
	total_customers DESC

-- Find the total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM
	customers
GROUP BY
	gender
ORDER BY
	total_customers DESC
	
-- Find total products by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM
	products
GROUP BY
	category
ORDER BY
	total_products DESC

-- What is the average costs in each category
SELECT
	category,
	AVG(cost) AS avg_cost
FROM
	products
GROUP BY
	category
ORDER BY
	avg_cost DESC
	
-- What is the total revenue generated for each category?
SELECT
	category,
	SUM(sales_amount) AS total_revenue
FROM
	fact_sales s
LEFT JOIN 
	products p ON s.product_key = p.product_key
GROUP BY
	category
ORDER BY
	total_revenue DESC

-- What is the total revenue generated by each customer?
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(sales_amount) AS total_revenue
FROM
	fact_sales s
LEFT JOIN 
	customers c ON s.customer_key = c.customer_key
GROUP BY
	c.customer_key,
	c.first_name,
	c.last_name
ORDER BY
	total_revenue DESC

-- What is the distribution of items sold across countries?
SELECT
	c.country,
	SUM(s.quantity) AS total_sold_quantity
FROM
	fact_sales s
LEFT JOIN 
	customers c ON s.customer_key = c.customer_key
GROUP BY
	c.country
ORDER BY
	total_sold_quantity DESC
